# Generated by Django 4.1.3 on 2023-07-25 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_description', models.CharField(max_length=500)),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 380803))),
            ],
        ),
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('post_title', models.CharField(max_length=50)),
                ('post_description', models.CharField(max_length=50)),
                ('TotalLikes', models.IntegerField()),
                ('TotalDisLikes', models.IntegerField()),
                ('IsLikedOrDisLiked', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 388806))),
                ('images', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 380803))),
            ],
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 388806))),
            ],
        ),
        migrations.CreateModel(
            name='Post_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 380803))),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.post')),
                ('tag_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post_like_or_dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('liked', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 388806))),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.post')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Post_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Image/None/Noimage.jpg', upload_to='images/')),
                ('CreatedDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 25, 1, 21, 3, 388806))),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.post')),
            ],
        ),
    ]
