# Generated by Django 4.1.3 on 2023-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_images',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post_like_or_dislike',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post_like_or_dislike',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post_tags',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post_tags',
            name='tag_id',
        ),
        migrations.DeleteModel(
            name='PostDetails',
        ),
        migrations.RemoveField(
            model_name='post',
            name='CreatedDate',
        ),
        migrations.AddField(
            model_name='post',
            name='IsLikedOrDisLiked',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='TotalDisLikes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='TotalLikes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Image/None/Noimage.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_weight',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Post_images',
        ),
        migrations.DeleteModel(
            name='Post_like_or_dislike',
        ),
        migrations.DeleteModel(
            name='Post_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Userdetail',
        ),
    ]
