# Generated by Django 4.1.3 on 2023-07-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_post_images_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_tag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
